### ISSUE TITLE
Switch to using everypolitician-ruby/popolo

### ISSUE THREAD

**Issue by chrismytton** [everypolitician/compare_morph_to_wikidata#2]
Rather than manually getting the popolo and digging through it for the identifiers we should instead be using [everypolitician-ruby](https://github.com/everypolitician/everypolitician-ruby).

**Comment by chrismytton** [comment]
If there are things that the libraries don't do already that would be useful, e.g. `person.wikidata_id`, then we should add that as it will be useful to others as well.

**Comment by tmtmtmtm** [comment]
> `person.wikidata_id`

NB: `.wikidata` is [already implemented](https://github.com/everypolitician/everypolitician-popolo/blob/4785fef26da455232240a10f79453fd0524a173c/lib/everypolitician/popolo/entity.rb#L58-L60) on `Entity`, so should be accessible anywhere that's already reconciled (e.g. people, parties, legislature, terms, areas)

**Comment by chrismytton** [comment]
Done in https://github.com/everypolitician/compare_morph_to_wikidata/commit/b944122afd67a78e7a4e350d6d2e3ff9c14463a9.

**Comment by chrismytton** [comment]
And improved in https://github.com/everypolitician/compare_morph_to_wikidata/commit/e07ef205cd2fd6af9cb75664ba6524f85e903ac9 😄
